[package]
name = "opencuboids-server-cli"
version = "0.0.0"
edition = "2021"
authors = ["Calbabreaker <calbabreaker@gmail.com>"]

[dependencies]
opencuboids-common = { path = "../common" }
opencuboids-server = { path = "../server" }
clap = { version = "3.2.16", features = ["derive"] }
