[package]
name = "opencuboids-server"
version = "0.0.0"
edition = "2021"
authors = ["Calbabreaker <calbabreaker@gmail.com>"]

[dependencies]
opencuboids-common = { path = "../common" }

log = "0.4.17"
glam = "0.21.3"
