[package]
name = "opencuboids-server"
version = "0.0.0"
edition = "2021"
authors = ["Calbabreaker <calbabreaker@gmail.com>"]

[dependencies]
log = "0.4.17"

opencuboids-common = { path = "../common" }
