[package]
name = "opencuboids-common"
version = "0.0.0"
edition = "2021"
authors = ["Calbabreaker <calbabreaker@gmail.com>"]

[dependencies]
bincode = "1.3.3"
env_logger = "0.10.0"
glam = { version = "0.22.0", features = ["serde"] }
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
